## 第一題_算閏年：
請定義一個函式，讀進一個年份，輸出是不是閏年。

提示：目前使用的格里高利曆閏年規則如下：

* 公元年分除以4不可整除，為平年。
* 公元年分除以4可整除但除以100不可整除，為閏年。
* 公元年分除以100可整除但除以400不可整除，為平年。
* 公元年分除以400可整除，為閏年。

In [1]:
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
def 年份(x):
    if x%4 != 0 :
        print(x,"為平年")
    elif x%4 == 0 and x%100 != 0:
        print(x,"為閏年")
    elif x%100 == 0 and x%400 !=0:
        print(x,"為平年")
    elif x%400 == 0:
        print(x,"為閏年")

In [3]:
年份(2222)
年份(2028)
年份(2100)
年份(4000)

2222 為平年
2028 為閏年
2100 為平年
4000 為閏年

## 第二題_請實作五乘五矩陣的矩陣加法函式：

In [4]:
def matrix_plus(m1, m2):
    mm1=np.array(m1)
    mm2=np.array(m2)
    return mm1+mm2

matrix_plus([[1,1,1,1,1],[2,2,2,2,2],[3,3,3,3,3],[4,4,4,4,4],[5,5,5,5,5]], 
            [[5,5,5,5,5],[4,4,4,4,4],[3,3,3,3,3],[2,2,2,2,2],[1,1,1,1,1]])

array([[6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6]])

## 第三題_錄取分數表格
小明今年考大學
依照 [“國文”, “英文”, “數甲”, “數乙”, “物理”, “化學”, “生物”, “歷史”, “地理”, “公民”]

他的分數分別是 [86.5, 79.4, 88.2, 96.5, 86.3, 76.8, 96.1, 78.5, 82.4, 88.6]

而他所想申請的大學各系採計的科目權重分別是
{
“土語系”: [2, 2, 0, 1, 0, 0, 0, 1, 1, 0],

“財政系”: [1, 1.5, 0, 1.5, 0, 0, 0, 0, 0, 0],

“金融系”: [1, 1.5, 0, 2, 0, 0, 0, 0, 0, 0],

“國貿系”: [1.5, 2, 0, 2, 0, 0, 0, 0, 0, 0],

“會計系”: [1.5, 2, 0, 2, 0, 0, 0, 1, 1, 0],

“法律系”: [1, 2, 0, 1, 0, 0, 0, 1, 0, 1],

“公行系”: [1, 1.5, 0, 1.25, 0, 0, 0, 0, 0, 1.25],

“應數系”: [1, 1, 1.5, 0, 1, 1, 0, 0, 0, 0],

“教育系”: [1.5, 2, 0, 1.25, 0, 0, 0, 1, 1, 0]
}

請幫他做出一個表格
* 第一欄顯示科系
* 接下來顯示權重 並標示科目
* 最後一欄顯示加權分數

In [5]:
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [6]:
weights=np.array([[2, 2, 0, 1, 0, 0, 0, 1, 1, 0],
               [1, 1.5, 0, 1.5, 0, 0, 0, 0, 0, 0],
               [1, 1.5, 0, 2, 0, 0, 0, 0, 0, 0],
               [1.5, 2, 0, 2, 0, 0, 0, 0, 0, 0],
               [1.5, 2, 0, 2, 0, 0, 0, 1, 1, 0],
               [1, 2, 0, 1, 0, 0, 0, 1, 0, 1],
               [1, 1.5, 0, 1.25, 0, 0, 0, 0, 0, 1.25],
               [1, 1, 1.5, 0, 1, 1, 0, 0, 0, 0],
               [1.5, 2, 0, 1.25, 0, 0, 0, 1, 1, 0]])

In [7]:
weights

array([[2.  , 2.  , 0.  , 1.  , 0.  , 0.  , 0.  , 1.  , 1.  , 0.  ],
       [1.  , 1.5 , 0.  , 1.5 , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ],
       [1.  , 1.5 , 0.  , 2.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ],
       [1.5 , 2.  , 0.  , 2.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ],
       [1.5 , 2.  , 0.  , 2.  , 0.  , 0.  , 0.  , 1.  , 1.  , 0.  ],
       [1.  , 2.  , 0.  , 1.  , 0.  , 0.  , 0.  , 1.  , 0.  , 1.  ],
       [1.  , 1.5 , 0.  , 1.25, 0.  , 0.  , 0.  , 0.  , 0.  , 1.25],
       [1.  , 1.  , 1.5 , 0.  , 1.  , 1.  , 0.  , 0.  , 0.  , 0.  ],
       [1.5 , 2.  , 0.  , 1.25, 0.  , 0.  , 0.  , 1.  , 1.  , 0.  ]])

In [8]:
name=["國文","英文","數甲","數乙","物理","化學","生物","歷史","地理","公民"]

In [9]:
school=["土語系","財政系","金融系","國貿系","會計系","法律系","公行系","應數系","教育系"]

In [10]:
df = pd.DataFrame(weights,columns=name,index=school)

In [11]:
df

      國文   英文   數甲    數乙   物理   化學   生物   歷史   地理    公民
土語系  2.0  2.0  0.0  1.00  0.0  0.0  0.0  1.0  1.0  0.00
財政系  1.0  1.5  0.0  1.50  0.0  0.0  0.0  0.0  0.0  0.00
金融系  1.0  1.5  0.0  2.00  0.0  0.0  0.0  0.0  0.0  0.00
國貿系  1.5  2.0  0.0  2.00  0.0  0.0  0.0  0.0  0.0  0.00
會計系  1.5  2.0  0.0  2.00  0.0  0.0  0.0  1.0  1.0  0.00
法律系  1.0  2.0  0.0  1.00  0.0  0.0  0.0  1.0  0.0  1.00
公行系  1.0  1.5  0.0  1.25  0.0  0.0  0.0  0.0  0.0  1.25
應數系  1.0  1.0  1.5  0.00  1.0  1.0  0.0  0.0  0.0  0.00
教育系  1.5  2.0  0.0  1.25  0.0  0.0  0.0  1.0  1.0  0.00

In [12]:
grade=np.array([86.5, 79.4, 88.2, 96.5, 86.3, 76.8, 96.1, 78.5, 82.4, 88.6])

In [13]:
mean = np.dot(weights ,grade)

In [14]:
df["加權分數"]=mean

In [15]:
df

      國文   英文   數甲    數乙   物理   化學   生物   歷史   地理    公民     加權分數
土語系  2.0  2.0  0.0  1.00  0.0  0.0  0.0  1.0  1.0  0.00  589.200
財政系  1.0  1.5  0.0  1.50  0.0  0.0  0.0  0.0  0.0  0.00  350.350
金融系  1.0  1.5  0.0  2.00  0.0  0.0  0.0  0.0  0.0  0.00  398.600
國貿系  1.5  2.0  0.0  2.00  0.0  0.0  0.0  0.0  0.0  0.00  481.550
會計系  1.5  2.0  0.0  2.00  0.0  0.0  0.0  1.0  1.0  0.00  642.450
法律系  1.0  2.0  0.0  1.00  0.0  0.0  0.0  1.0  0.0  1.00  508.900
公行系  1.0  1.5  0.0  1.25  0.0  0.0  0.0  0.0  0.0  1.25  436.975
應數系  1.0  1.0  1.5  0.00  1.0  1.0  0.0  0.0  0.0  0.00  461.300
教育系  1.5  2.0  0.0  1.25  0.0  0.0  0.0  1.0  1.0  0.00  570.075